<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>VoiceMeeter AEC</AssemblyName>
    <RootNamespace>VoiceMeeterAEC</RootNamespace>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Version>1.1.1</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Authors>BeeeFX</Authors>
    <Product>VoiceMeeter AEC</Product>
    <Description>Simple acoustic echo cancellation for VoiceMeeter Banana and Potato.</Description>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\app-icon-256.png" />
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\voicemeeter-patch-insert.png" />
    <Resource Include="Assets\voicemeeter-banana-patch-insert.png" />
  </ItemGroup>
</Project>
